"""LLM-written commentary on the backtest results.

Uses the Anthropic API when ANTHROPIC_API_KEY is set. The model only sees the
numbers we hand it and is told not to invent any others. Without a key, the
prompt is saved so you can paste it into any chat assistant.
"""

from __future__ import annotations

import os
from pathlib import Path

DEFAULT_MODEL = os.environ.get("PORTOPT_LLM_MODEL", "claude-sonnet-5-5")

SYSTEM = (
    "You are a buy-side quantitative analyst writing a short results note for a "
    "portfolio-construction research project. Be precise and sober. Use only the "
    "numbers provided; never invent statistics. Where a conclusion rests on one "
    "historical path, say so."
)


def build_prompt(summary_md: str, setup: dict, notes: list[str] | None = None) -> str:
    setup_lines = "\n".join(f"- {k}: {v}" for k, v in setup.items())
    extra = "\n".join(f"- {n}" for n in (notes or []))
    return f"""Write a commentary of about 250 words on this out-of-sample backtest.

Setup
{setup_lines}

Out-of-sample results (monthly returns, annualized)
{summary_md}

Additional facts
{extra or "- none"}

Cover, in plain prose (no headings, no bullet lists):
1. Which allocation held up best out of sample, judged on risk-adjusted return and drawdown, and the cost in turnover. Use the bootstrap p-values to say whether any Sharpe gap versus equal weight is statistically meaningful; do not call a gap real if p >= 0.05.
2. How max-Sharpe compared with the estimation-light portfolios (equal weight, min variance, risk parity), and why noisy expected-return estimates explain the gap.
3. What Ledoit-Wolf covariance shrinkage changed, and what it cannot fix (it shrinks the covariance, not the expected returns).
4. One caveat about drawing conclusions from a single historical sample.
"""


def generate(prompt: str, model: str = DEFAULT_MODEL, max_tokens: int = 900) -> str:
    import anthropic

    client = anthropic.Anthropic()  # reads ANTHROPIC_API_KEY
    msg = client.messages.create(
        model=model,
        max_tokens=max_tokens,
        system=SYSTEM,
        messages=[{"role": "user", "content": prompt}],
    )
    return "".join(block.text for block in msg.content if block.type == "text").strip()


def write_commentary(prompt: str, out_dir: Path, enabled: bool = True) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "commentary_prompt.md").write_text(prompt)
    path = out_dir / "commentary.md"

    if not enabled:
        return out_dir / "commentary_prompt.md"
    if not os.environ.get("ANTHROPIC_API_KEY"):
        print("  ANTHROPIC_API_KEY not set: saved the prompt to commentary_prompt.md instead.")
        return out_dir / "commentary_prompt.md"
    try:
        text = generate(prompt)
    except Exception as exc:  # noqa: BLE001 - commentary is optional, never fail the run
        print(f"  LLM commentary skipped ({type(exc).__name__}: {exc}). Prompt saved.")
        return out_dir / "commentary_prompt.md"

    path.write_text(f"# AI commentary\n\n_Generated by `{DEFAULT_MODEL}` from the results table only._\n\n{text}\n")
    return path
